import { GenderEnum, LookingforEnum, PersonPreview, User } from './types';
import { Types } from 'mongoose';
import { mockPersonalQuestionsList } from '../personalQuestions/mockups';
import { HoroscopeEnum } from '../about';

export const mockupGeneralUserList: User[] = [
   {
      _id: new Types.ObjectId(),
      name: 'Elisa',
      last_name: 'Martinez',
      password: '99adc231b045331e514a516b4b7680f588e3823213abe901738bc3ad67b2f6fcb3c64efb93d18002588d3ccc1a49efbae1ce20cb43df36b38651f11fa75678e8',
      email: 'eliza@eliza.com',
      country: 'México',
      city: 'CDMX',
      phone: '+525512907846',
      image_profile: 'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      gallery: [
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      ],
      age: 20,
      gender: GenderEnum.Female,
      preference: 'Lo que no sea humano',
      about: {
         horoscope: HoroscopeEnum.AQUARIUS,
         personal_questions: mockPersonalQuestionsList,
         description: "I'm looking a new experience",
      },
      lookingfor: LookingforEnum.LongRelationship,
      verified: true,
   },
   {
      _id: new Types.ObjectId(),
      name: 'Elisa',
      last_name: 'Martinez',
      password: '99adc231b045331e514a516b4b7680f588e3823213abe901738bc3ad67b2f6fcb3c64efb93d18002588d3ccc1a49efbae1ce20cb43df36b38651f11fa75678e8',
      email: 'eliza@eliza.com',
      country: 'México',
      city: 'CDMX',
      phone: '+525512907846',
      image_profile: 'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      gallery: [
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
         'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      ],
      age: 20,
      gender: GenderEnum.Female,
      preference: 'Lo que no sea humano',
      about: {
         horoscope: HoroscopeEnum.AQUARIUS,
         personal_questions: mockPersonalQuestionsList,
         description: "I'm looking a new experience",
      },
      lookingfor: LookingforEnum.LongRelationship,
      verified: true,
   },
];

export const mockGeneralUser: User = {
   _id: new Types.ObjectId(),
   name: 'Elisa',
   last_name: 'Martinez',
   password: '99adc231b045331e514a516b4b7680f588e3823213abe901738bc3ad67b2f6fcb3c64efb93d18002588d3ccc1a49efbae1ce20cb43df36b38651f11fa75678e8',
   email: 'eliza@eliza.com',
   country: 'México',
   city: 'CDMX',
   phone: '+525512907846',
   image_profile: 'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
   gallery: [
      'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
      'https://www.okchicas.com/wp-content/uploads/2020/08/outfits-y-conjuntos-con-todo-el-estilo-de-una-e-girl-17.png',
   ],
   age: 20,
   gender: GenderEnum.Female,
   preference: 'Lo que no sea humano',
   about: {
      horoscope: HoroscopeEnum.AQUARIUS,
      personal_questions: mockPersonalQuestionsList,
      description: "I'm looking a new experience",
   },
   lookingfor: LookingforEnum.LongRelationship,
   verified: true,
};

export const mockopPersonsPreview: PersonPreview[] = [
   {
      _id: '_id1',
      name: 'Probemio',
      last_name: 'testino',
      country: 'México',
      city: 'CDMX',
      phone: '+525512907846',
      image_profile: 'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
      gallery: [
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
      ],
      age: 40,
      gender: GenderEnum.Other,
      preference: 'Lo que no sea humano',
      about: {
         horoscope: HoroscopeEnum.AQUARIUS,
         personal_questions: mockPersonalQuestionsList,
         description: "I'm looking a new experience",
      },
   },
   {
      _id: '_id1',
      name: 'Probemio',
      last_name: 'testino',
      country: 'México',
      city: 'CDMX',
      phone: '+525512907846',
      image_profile: 'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
      gallery: [
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
      ],
      age: 40,
      gender: GenderEnum.Other,
      preference: 'Lo que no sea humano',
      about: {
         horoscope: HoroscopeEnum.CAPRICORN,
         personal_questions: mockPersonalQuestionsList,
         description: "I'm looking a new experience",
      },
   },
   {
      _id: '_id1',
      name: 'Probemio',
      last_name: 'testino',
      country: 'México',
      city: 'CDMX',
      phone: '+525512907846',
      image_profile: 'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
      gallery: [
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
         'https://pickaface.net/gallery/avatar/unr_test_180821_0925_9k0pgs.png',
      ],
      age: 40,
      gender: GenderEnum.Other,
      preference: 'Lo que no sea humano',
      about: {
         horoscope: HoroscopeEnum.AQUARIUS,
         personal_questions: mockPersonalQuestionsList,
         description: "I'm looking a new experience",
      },
   },
];
